### ISSUE TITLE
Request: Publish to npm?

### ISSUE THREAD

**Issue by nathanfiedler** [easy-webpack/config-sass#1]
Would it be possible to publish this project to npm? I would love to use it in one of my projects but noticed that it isn't available using `npm install` like all of the other easy-webpack repositories (listed [here](https://www.npmjs.com/~easy-webpack)). Thanks much!

**Comment by niieani** [comment]
I'll publish this project 🎱 soon.

**Comment by niieani** [comment]
Published.

**Comment by nathanfiedler** [comment]
Thank you!
