### ISSUE TITLE
Unmet peer dependency

### ISSUE THREAD

**Issue by jonathaneckman** [easy-webpack/config-sass#16]
I am getting the following trying to install your package. 
```
+-- @easy-webpack/config-sass@2.0.1
| -- @easy-webpack/config-css@3.1.0
|   -- css-loader@0.25.0
-- UNMET PEER DEPENDENCY webpack@2.1.0-beta.22
```
Webpack is installed:
```
"webpack": "2.1.0-beta.22",
"webpack-dev-server": ">=2.1.0-beta.0 || ^2.1.0"
```

**Comment by niieani** [comment]
I believe you're getting the error from somewhere else. This package does not depend on webpack. See https://github.com/easy-webpack/config-sass/blob/master/package.json#L49-L54

**Comment by jonathaneckman** [comment]
I think you are right. I didnt track down where it came from, but updating webpack to beta globally fixed it.
