### ISSUE TITLE
Support for .sass files

### ISSUE THREAD

**Issue by alpox** [easy-webpack/config-sass#7]
Hi again!

I wanted to add sass css files to my project but it seems that config-sass only supports scss (Though the name). Is there a way you will support .sass too in future?

**Comment by niieani** [comment]
.sass files should now be passed to the compiler. The NPM package will be updated in ~10-15 minutes.

**Comment by alpox** [comment]
Thanks @niieani in the meantime i figured out that this works too:

```
require('@easy-webpack/config-css')
       ({ test: /\.(css|sass|scss)$/i, additionalLoaders: ['sass'], filename: 'styles.css', allChunks: true, sourceMap: false }),
```
