### ISSUE TITLE
Minification and cache busting

### ISSUE THREAD

**Issue by stevies** [easy-webpack/config-sass#8]
Using easy-webpack/config-sass with an aurelia app based on ES6 webpack skeleton:

https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-esnext-webpack

But with scss files added in place of css files.

I have configured as follows for my production builld:

```
require('@easy-webpack/config-sass')
    ({filename: 'main.css', allChunks: true, sourceMap: false)
```

Works OK, but generates an unminified main.css file.  

How can the webpack.config.js be configured to minify the generated css file for a production build?

Also, how can the main.css file be renamed with a version hash name like the other app bundle files? -eg

```
app.84b14c23bfb92e7d6616.bundle.js
```

**Comment by stevies** [comment]
Appears I can do this - config-generate-index-html: 

```
 require('@easy-webpack/config-generate-index-html')
      ({
        minify: true, overrideOptions: {
            'hash': true
        }
      }),
```

That will append a query string param. eg:

```
  <link href="main.css?75a179ceb750eb0b8da6" rel="stylesheet">
```

Probably good enough.  But it also does it to js files - eg:

```
<script type="text/javascript" src="aurelia-bootstrap.1ab36e32c7217219a891.bundle.js?75a179ceb750eb0b8da6"></script>
<script type="text/javascript" src="aurelia.a303ac040b99138aa045.bundle.js?75a179ceb750eb0b8da6"></script>
<script type="text/javascript" src="vendor.dc62700a4bac67303899.bundle.js?75a179ceb750eb0b8da6"></script>
<script type="text/javascript" src="app.f471f552dda3918e7fac.bundle.js?75a179ceb750eb0b8da6"></script>
```

which is a bit overkill.  Still would be nice to know if it is possible to just rename the css file and link to it.

**Comment by niieani** [comment]
Why would you want to append the CSS filename with a hash? Anyway, you CSS/SASS/LESS output for production build (ENV==production) should be minified. If they're not, it's a bug.

**Comment by stevies** [comment]
To cache-bust it - same as for the js files - eg.  

```
main.75a179ceb750eb0b8da6.css 
```

Ideally, you'd configure your server to have a far future cache expiry date for the css file, and change the name of the file if it ever gets updated.

File is minified OK.

I can achieve much the same thing by leaving the css embedded in the js file (which does get versioned)- but not sure if it is better to just serve up the css as a normal link.

**Comment by niieani** [comment]
I know the reasons, just didn't understand how that's related to not being able to minify it :)
Let me know if you need me to reopen this.

**Comment by stevies** [comment]
Sorry - my fault for asking 2 questions in one github issue.  

For clarification - if i have:

```
require('@easy-webpack/config-sass')
    ({filename: 'main.css', allChunks: true, sourceMap: false)
```

Then my generated css come out unminified - formatetd like:

```
@charset "UTF-8";
.grid-row:after, #content:after, .notice:after, .panel:after, fieldset:after, .form-section:after, .form-group:after, .form-block:after, .breadcrumbs ol:after, #aurelia-content:after {
  content: "";
  display: block;
  clear: both; }

#content, #aurelia-content {
  max-width: 960px;
  margin: 0 15px; }
  @media (min-width: 641px) {
    #content, #aurelia-content {
      margin: 0 30px; } }
  @media (min-width: 1020px) {
    #content, #aurelia-content {
      margin: 0 auto; } }
```

If this is a bug, then please reopen this ticket.  

Or maybe I have just missed out some config or have incorrect order, or something.  If so, please let me know if I can do something to change that. 

Here's my production entry from webpack.config.js.

```
case 'production':
    config = generateConfig(
      baseConfig,

      require('@easy-webpack/config-env-production')
      ({compress: true}),

      require('@easy-webpack/config-eslint')(),

      require('@easy-webpack/config-aurelia')
      ({root: rootDir, src: srcDir, title: title, baseUrl: baseUrl}),

      require('@easy-webpack/config-babel')(),
      require('@easy-webpack/config-html')(),
      require('@easy-webpack/config-json')(),

      require('@easy-webpack/config-sass')
      ({filename: 'gds.css', allChunks: true, sourceMap: false}),

      require('@easy-webpack/config-fonts-and-images')(),
      require('@easy-webpack/config-global-bluebird')(),
      require('@easy-webpack/config-global-regenerator')(),
      require('@easy-webpack/config-generate-index-html')
      ({
        minify: false, overrideOptions: {
          'xhtml': true,
          'hash': true
        }
      }),

      require('@easy-webpack/config-copy-files')
      ({
        patterns: [
          {from: 'favicon.ico', to: 'favicon.ico'},
          {from: 'config/**/*', to: './'}
        ]
      }),

      require('@easy-webpack/config-common-chunks-simple')
      ({appChunkName: 'app', firstChunk: 'aurelia-bootstrap'}),

      require('@easy-webpack/config-uglify')
      ({debug: false})
    );
    break;
```

My other question was about cache-busting. Perhaps I should have put that in its own issue.  I'll do that if you want - still needs an answer.

**Comment by niieani** [comment]
OK, I'm pretty busy at the time, abut I'll add this to my ToDo list. I'll also try and implement both cache-busting and minification (if it really doesn't work) to the aurelia webpack skeleton, so you'll be able to copy the proper config from there.

**Comment by mikeesouth** [comment]
@stevies & @niieani 
**Cache busting** can be achieved with appending `.[hash]` like this:
```
css({ filename: 'styles.[hash].css', allChunks: true, sourceMap: false }),
sass({ filename: 'styles.[hash].css', allChunks: true, sourceMap: false }),
```
This uses the hash from the source files but for my needs it is more than good enough, i.e: if I only change CSS the hash won't change.

**Minification** does not work for me either, have you had any progress with this?

**Comment by Holi0317** [comment]
Assume you are working with webpack 2, minification flag can be passed with `webpack.LoaderOptionsPlugin`.

css-loader will do the minification using cssnano.

Source: https://github.com/webpack/css-loader#minification

Define a plugin in your webpack config file.
```js
{
  plugins: [
    new webpack.LoaderOptionsPlugin({
      minimize: ENV === 'production'
    })
  ]
}
```

But webpack has said [this plugin will be removed later](https://webpack.js.org/plugins/loader-options-plugin/). This is just a temporary solution. config-css and config-sass should be able to accept loader options.

**Comment by mikeesouth** [comment]
@Holi0317 Thanks. It works great. I notice that comments (/* comments) are not removed from the minified result - shouldn't those be minimized? It's a minor issue but I'm curious.

**Comment by Holi0317** [comment]
@mikeesouth I just tried that on my current project and did not find any comment in it. Are those comments about license? [cssnano may keep those](http://cssnano.co/optimisations/discardComments/).

**Comment by mikeesouth** [comment]
@Holi0317 Ah, you are absolutely correct. It's license information.

@niieani as mentioned by @Holi0317 this "workaround" is OK but temporary and it would be great if config-css and config-sass would accept loader options.

**Comment by niieani** [comment]
@mikeesouth Once the underlying loaders support native loader options we can do it. For now adding LoaderOptionsPlugin globally is a no-go, because you can only add it once and it overrides all the options accessible by a given plugin for a given test. So users will have to add those manually if they know what they're doing.
