### ISSUE TITLE
Generated config fails webpack validation: [1] "loaders" must be an array

### ISSUE THREAD

**Issue by mdurling** [easy-webpack/config-sass#9]
webpack@2.1.0-beta.22
webpack-validator@2.2.9
@easy-webpack/config-sass@1.2.0

```
{
  "metadata": {
    "port": 9000,
    "host": "localhost",
    "ENV": "development",
    "HMR": false,
    "extractTextInstances": {}
  },
  "module": {
    "loaders": [
      {
        "test": {},
        **"loaders" [1]: "C:\\Git\\proximus\\node_modules\\extract-text-webpack-plugin\\loader.js?{\"id\":1,\"omit\":0,\"remove\":true,\"notExtractLoader\":\"style\"}!css!sass"**
      }
    ]
  },
  "plugins": [
    {
      "filename": "styles.css",
      "id": 1,
      "options": {
        "sourceMap": false,
        "allChunks": true
      }
    }
  ]
}
```

**[1] "loaders" must be an array**

**Comment by niieani** [comment]
The output of what are you citing here?

**Comment by mdurling** [comment]
webpack-validator@2.2.9

https://www.npmjs.com/package/webpack-validator

**Comment by niieani** [comment]
Is this fixed in the recent major versions?

**Comment by mdurling** [comment]
No. It works with webpack@2.1.0-beta.22 and all of the compatible
@easy-webpack packages

With webpack@2.1.0-beta.25 and all of the updated @easy-webpack packages, I
get errors, perhaps related to Aurelia. So, we're in a bit of a holding
pattern on being able to move forward with webpack.

Invalid configuration object. Webpack has been initialised using a
configuration object that does not match the API schema.
- configuration has an unknown property 'metadata'. These properties are
  valid:
  object { amd?, bail?, cache?, context?, dependencies?, devServer?,
  devtool?, entry, externals?, loader?, module?, name?, node?, output?,
  plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?,
  resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
  For typos: please correct them.
  For loader options: webpack 2 no longer allows custom properties in
  configuration.
   Loaders should be updated to allow passing options via loader options
  in module.rules.
   Until loaders are updated one can use the LoaderOptionsPlugin to pass
  these options to the loader:
   plugins: {
     new webpack.LoaderOptionsPlugin({
       // test: /.xxx$/, // may apply this only for some modules
       options: {
         metadata: ...
       }
     })
   }
- configuration.entry['app'] should be one of these:
  string | [string]
  The entry point for one output file.
- configuration.entry should be one of these:
  object { <key>: string | [string] } | string | [string]
  The entry point(s) of the compilation.

This is the entry that it complains about:

  entry: {
    'app': [/\* this is filled by the aurelia-webpack-plugin */],
    'aurelia-bootstrap': coreBundles.bootstrap,
    'aurelia': coreBundles.aurelia.filter(pkg =>
coreBundles.bootstrap.indexOf(pkg) === -1)
  }

And this is what's in the metadata property that it doesn't like:

{
  "port": 9000,
  "host": "localhost",
  "ENV": "development",
  "HMR": false,
  "title": "inMotion Proximus",
  "baseUrl": "/",
  "root": "C:\Git\proximus",
  "src": "C:\Git\proximus\src",
  "extractTextInstances":
Map {
  'styles.css' => ExtractTextPlugin {
  filename: 'styles.css',
  id: 1,
  options: { allChunks: true, sourceMap: false } } }
}

On Wed, Nov 9, 2016 at 8:59 AM Bazyli Brzóska notifications@github.com
wrote:

Is this fixed in the recent major versions?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/easy-webpack/config-sass/issues/9#issuecomment-259420680,
or mute the thread

**Comment by niieani** [comment]
All of this has been fixed (you can see the examples in the latest major versions of easy-webpack configs as shown in the most recent [aurelia skeleton](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript-webpack)), that's why I asked whether this specific issue is still a problem. Closing.

**Comment by mdurling** [comment]
Thank your for your timely response...

I just updated all of the packages again and grabbed the latest skeleton
webpack config and it is much closer.

It appears the errors I am getting now relate to how scss files and image
files are imported and referenced from my Aurelia project.

Previously, I would import styles simply with:

import '../node_modules/materialize-css/sass/materialize.scss'
import '../styles/styles.scss'

in my main.ts file and they would get bundled

Also, I could load images as follows:

logo = require('../../../images/logo.png')

Now, however, I get the following errors:

ERROR in ./styles/styles.scss
Module parse failed: C:\Git\proximus\styles\styles.scss Unexpected token
(1:15)
You may need an appropriate loader to handle this file type.
| div.brand-logo {
|   width: 150px;
|   height: 100%;
 @ ./src/main.ts 11:0-32
 @ multi app

ERROR in ./~/materialize-css/sass/materialize.scss
Module parse failed:
C:\Git\proximus\node_modules\materialize-css\sass\materialize.scss
Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @charset "UTF-8";
|
| // Mixins
 @ ./src/main.ts 10:0-64
 @ multi app

ERROR in [default] C:\Git\proximus\src\routes\login\login.ts:26:9
Cannot find name 'require'.

On Wed, Nov 9, 2016 at 3:17 PM Bazyli Brzóska notifications@github.com
wrote:

All of this has been fixed (you can see the examples in the latest aurelia
skeleton
https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript-webpack),
that's why I asked whether this specific issue is still a problem. Closing.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/easy-webpack/config-sass/issues/9#issuecomment-259515142,
or mute the thread

**Comment by niieani** [comment]
Which version of config-sass are you using?

**Comment by mdurling** [comment]
@easy-webpack/config-sass@1.2.0

It looks like 2.0.0 has not been published to npm

On Wed, Nov 9, 2016 at 4:21 PM Bazyli Brzóska notifications@github.com
wrote:

Which version of config-sass are you using?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/easy-webpack/config-sass/issues/9#issuecomment-259530097,
or mute the thread

**Comment by niieani** [comment]
just published 2.0.1

**Comment by mdurling** [comment]
Thank you so much!

I think I have everything working again!

I appreciate how responsive you have been.

We are loving building with Aurelia!

**Comment by mdurling** [comment]
One more question. Once we deployed to our test server, we are getting the following error. Any thoughts?

Navigated to http://proximus-dev.inmotionnow.com/
aurelia-metadata.js:37Uncaught TypeError: Reflect.getOwnMetadata is not a function(…)getOwn @ aurelia-metadata.js:37getOrCreateOwn @ aurelia-metadata.js:43deco @ aurelia-templating.js?e612:4602bindable @ aurelia-templating.js?e612:4621(anonymous function) @ router-view.js?0f13:43_applyDecoratedDescriptor @ router-view.js?0f13:42(anonymous function) @ router-view.js?0f13:23747 @ aurelia.8396ec4….bundle.js:14317__webpack_require__ @ bootstrap 75f0120…?f004:77aurelia-templating-router @ aurelia-templating-router.js?ad04:12__webpack_require__ @ bootstrap 75f0120…?f004:77262 @ aurelia.8396ec4….bundle.js:11527__webpack_require__ @ bootstrap 75f0120…?f004:77(anonymous function) @ bootstrap 75f0120…?f004:160(anonymous function) @ bootstrap 75f0120…?f004:160
app.2415c15….bundle.js:24Uncaught TypeError: Cannot read property 'call' of undefined(…)**webpack_require** @ app.2415c15….bundle.js:2478 @ app.2415c15….bundle.js:24549__webpack_require__ @ app.2415c15….bundle.js:24261 @ app.2415c15….bundle.js:19045__webpack_require__ @ app.2415c15….bundle.js:24(anonymous function) @ app.2415c15….bundle.js:66(anonymous function) @ app.2415c15….bundle.js:69
bluebird.js?e366:1546Unhandled rejection TypeError: Cannot read property 'call' of undefined
    at **webpack_require** (http://proximus-dev.inmotionnow.com/aurelia-bootstrap.29d0845bbbfe4dab5243.bundle.js:78:37)
    at http://proximus-dev.inmotionnow.com/aurelia-bootstrap.29d0845bbbfe4dab5243.bundle.js:7798:24
From previous event:
    at Promise.then._this2.modulesBeingLoaded.(anonymous function) (http://proximus-dev.inmotionnow.com/aurelia-bootstrap.29d0845bbbfe4dab5243.bundle.js:7797:81)
From previous event:
    at WebpackLoader._import (http://proximus-dev.inmotionnow.com/aurelia-bootstrap.29d0845bbbfe4dab5243.bundle.js:7783:18)
    at WebpackLoader.loadModule (http://proximus-dev.inmotionnow.com/aurelia-bootstrap.29d0845bbbfe4dab5243.bundle.js:7841:17)
    at http://proximus-dev.inmotionnow.com/aurelia-bootstrap.29d0845bbbfe4dab5243.bundle.js:7623:12
From previous event:
    at run (http://proximus-dev.inmotionnow.com/aurelia-bootstrap.29d0845bbbfe4dab5243.bundle.js:7620:24)
    at Object.<anonymous> (http://proximus-dev.inmotionnow.com/aurelia-bootstrap.29d0845bbbfe4dab5243.bundle.js:7645:1)
    at Object.aurelia-bootstrapper-webpack (http://proximus-dev.inmotionnow.com/aurelia-bootstrap.29d0845bbbfe4dab5243.bundle.js:7646:30)
    at __webpack_require__ (http://proximus-dev.inmotionnow.com/aurelia-bootstrap.29d0845bbbfe4dab5243.bundle.js:78:38)
    at Object.263 (http://proximus-dev.inmotionnow.com/aurelia-bootstrap.29d0845bbbfe4dab5243.bundle.js:734:1)
    at **webpack_require** (http://proximus-dev.inmotionnow.com/aurelia-bootstrap.29d0845bbbfe4dab5243.bundle.js:78:38)
    at http://proximus-dev.inmotionnow.com/aurelia-bootstrap.29d0845bbbfe4dab5243.bundle.js:161:18
    at http://proximus-dev.inmotionnow.com/aurelia-bootstrap.29d0845bbbfe4dab5243.bundle.js:164:10printWarning @ bluebird.js?e366:1546formatAndLogError @ bluebird.js?e366:1262fireRejectionEvent @ bluebird.js?e366:1287Promise._notifyUnhandledRejection @ bluebird.js?e366:734(anonymous function) @ bluebird.js?e366:154

**Comment by niieani** [comment]
Looks like the webpack bug we've been hitting once in a while. A fix is coming soon.
